##################################################
# Run Mr Coxall's Super Linter against code base #
##################################################

---
name: Mr Coxall's Super Linter

on: [push, pull_request]

jobs:
  run-linters:
    name: Mr Coxall's Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository 🚦
        uses: actions/checkout@main
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Run GitHub Super Linter 🚀
        uses: super-linter/super-linter@main
        env:
          VALIDATE_ALL_CODEBASE: true
          LINTER_RULES_PATH: /
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_TYPESCRIPT_ES: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
